### ISSUE TITLE
[BUG] Blog Posts After the Year 2022 Are Not Processed

### ISSUE THREAD

**Issue by MicahBird** [gethinode/hinode#143] opened 2023-02-10 18:53 UTC
**Describe the bug**
When creating a blog post that is after the year 2022, the site doesn't build a page for that post. However, no error is outputted to the logs, and this could also be my error.

**To reproduce**
1. Go to `content/en/blog/`
2. Write a blog post with any year after the year 2022.
3. Go to `Blog` or `Tags` page on website
4. No page is listed for that post

**Log file**
No error is outputted, only the following:
```
Change detected, rebuilding site.
2023-02-10 11:43:45.013 -0700
Source changed WRITE         "[REDACTED]/content/en/blog/2023/lorum-ipsum.md"
Total in 59 ms
```

**Environment (please complete the following information):**
 - Host OS: Ubuntu 22.10
 - Node version: node v18.7.0
 - Hugo version: hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
 - Browser: Version 109.0.5414.119 (Official Build) (64-bit)

**This is an awesome project and Hugo theme, and I hope to make it better!**

**Comment by markdumay** [comment] 2023-02-11 16:46
Great to hear your like the theme. Looking at your example, it appears you would like to list content for a specific year. By design, Hinode lists all content within the same section, regardless of any subfolders. So the url `/blog` would list all blog posts. The order can be specified in the [list configuration](https://gethinode.com/docs/0.8/configuration/layout/#configuration-2).

Pending on your intent, you might want to revise the [permalink configuration](https://gohugo.io/content-management/urls/#permalinks-configuration-example). For example, you could add the following code to `config/_default/config.toml`:

```toml
[permalinks]
    blog = '/:year/:month/:title/'
```

If you still intent to create a subfolder `2023`, you should make sure it is configured as a [list page](https://gohugo.io/templates/lists/#what-is-a-list-page-template). Add a file `_index.md` to the `2023` folder, for example with the following content:

```html
---
author: Mark Dumay
title: Blog
---
```

You would still need to create a custom list page template in `layouts/_default` though.

**Comment by markdumay** [comment] 2023-02-20 09:41
I'm closing the issue for now, let me know if you'd like to reopen it.

**Closed by markdumay** 2023-02-20 09:41 UTC
Labels: bug
