### ISSUE TITLE
[BUG] Flash of unstyled content

### ISSUE THREAD

**Issue by TommyTran732** [gethinode/hinode#1084] opened 2024-08-11 19:39 UTC
## Describe the bug

"Flash of unstyled content" happens when loading a new page.

## To reproduce

1. Visit Hinode's demo site in dark mode.
2. Click on random pages
3. See the white flash when pages load

**Comment by markdumay** [comment] 2024-08-12 06:08
Thanks for reporting this, it appears to be a duplicate of #981. I've updated the original issue, which still contained placeholders.

**Closed by markdumay** 2024-08-12 06:08 UTC
Labels: bug, duplicate
